"""complete_schema

Revision ID: 60377d95d69b
Revises: 
Create Date: 2026-06-30 05:41:05.925008

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '60377d95d69b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
